# Custom exceptions belong in this module.

class pytmError(Exception):
	pass

